export const NETWORK_GOES_ONLINE = "NETWORK_GOES_ONLINE";
export const NETWORK_GOES_OFFLINE = "NETWORK_GOES_OFFLINE";



export const CORDOVA_DEVICE_READY = "CORDOVA_DEVICE_READY";



export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUESTING = "USER_LOGIN_REQUESTING";
export const USER_LOGIN_REQUEST_SUCCESSFUL = "USER_LOGIN_REQUEST_SUCESSFUL";
export const USER_LOGIN_REQUEST_FAILED = "USER_LOGIN_REQUEST_FAILED";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_REQUESTING = "USER_UPDATE_REQUESTING";
export const USER_UPDATE_REQUEST_SUCCESSFUL = "USER_UPDATE_REQUEST_SUCCESSFUL";
export const USER_UPDATE_REQUEST_FAILED = "USER_UPDATE_REQUEST_FAILED";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_REQUESTING = "USER_LOGOUT_REQUESTING";
export const USER_LOGOUT_REQUEST_SUCCESSFUL = "USER_LOGOUT_REQUEST_SUCCESSFUL";
export const USER_LOGOUT_REQUEST_FAILED = "USER_LOGOUT_REQUEST_FAILED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_REQUESTING = "USER_REGISTER_REQUESTING";
export const USER_REGISTER_REQUEST_SUCCESSFUL = "USER_REGISTER_REQUEST_SUCCESSFUL";
export const USER_REGISTER_REQUEST_FAILED = "USER_REGISTER_REQUEST_FAILED";

export const USER_OPTIONS_LOAD_REQUEST = "USER_OPTIONS_LOAD_REQUEST";
export const USER_OPTIONS_LOAD_REQUESTING = "USER_OPTIONS_LOAD_REQUESTING";
export const USER_OPTIONS_LOAD_REQUEST_SUCCESSFUL = "USER_OPTIONS_LOAD_REQUEST_SUCCESSFUL";
export const USER_OPTIONS_LOAD_REQUEST_FAILED = "USER_OPTIONS_LOAD_REQUEST_FAILED";

export const USER_OPTIONS_SAVE_REQUEST = "USER_OPTIONS_SAVE_REQUEST";
export const USER_OPTIONS_SAVE_REQUESTING = "USER_OPTIONS_SAVE_REQUESTING";
export const USER_OPTIONS_SAVE_REQUEST_SUCCESSFUL = "USER_OPTIONS_SAVE_REQUEST_SUCCESSFUL";
export const USER_OPTIONS_SAVE_REQUEST_FAILED = "USER_OPTIONS_SAVE_REQUEST_FAILED";

export const USER_OPTIONS_UNLOAD_REQUEST = "USER_OPTIONS_UNLOAD_REQUEST";



export const LOCATION_GET_REQUEST = "LOCATION_GET_REQUEST";
export const LOCATION_GET_REQUEST_SUCCESSFUL = "LOCATION_GET_REQUEST_SUCCESSFUL";
export const LOCATION_GET_REQUEST_FAILED = "LOCATION_GET_REQUEST_FAILED";

export const LOCATION_WATCH_START = "LOCATION_WATCH_START";
export const LOCATION_WATCH_START_SUCCESSFUL = "LOCATION_WATCH_START_SUCCESSFUL";
export const LOCATION_WATCH_START_FAILED = "LOCATION_WATCH_START_FAILED";
export const LOCATION_WATCH_UPDATE_SUCCESSFUL = "LOCATION_WATCH_UPDATE_SUCCESSFUL";
export const LOCATION_WATCH_UPDATE_FAILED = "LOCATION_WATCH_UPDATE_FAILED";

export const LOCATION_UPDATE_SUBMIT = "LOCATION_UPDATE_SUBMIT";
export const LOCATION_UPDATE_SUBMITTING = "LOCATION_UPDATE_SUBMITTING";
export const LOCATION_UPDATE_SUBMIT_SUCCESSFUL = "LOCATION_UPDATE_SUBMIT_SUCCESSFUL";
export const LOCATION_UPDATE_SUBMIT_FAILED = "LOCATION_UPDATE_SUBMIT_FAILED";

export const LOCATION_WATCH_STOP = "LOCATION_WATCH_STOP";
export const LOCATION_WATCH_STOP_SUCCESSFUL = "LOCATION_WATCH_STOP_SUCCESSFUL";
export const LOCATION_WATCH_STOP_FAILED = "LOCATION_WATCH_STOP_FAILED";

export const LOCATION_NEARBY_REQUEST = "LOCATION_NEARBY_REQUEST";
export const LOCATION_NEARBY_REQUESTING = "LOCATION_NEARBY_REQUESTING";
export const LOCATION_NEARBY_REQUEST_SUCCESSFUL = "LOCATION_NEARBY_REQUEST_SUCCESSFUL";
export const LOCATION_NEARBY_REQUEST_FAILED = "LOCATION_NEARBY_REQUEST_FAILED";
export const LOCATION_NEARBY_CLEAR = "LOCATION_NEARBY_CLEAR";



export const SOCKET_START_REQUEST = "SOCKET_START_REQUEST";
export const SOCKET_START_REQUESTING = "SOCKET_START_REQUESTING";
export const SOCKET_START_REQUEST_SUCCESSFUL = "SOCKET_START_REQUEST_SUCCESSFUL";
export const SOCKET_START_REQUEST_FAILED = "SOCKET_START_REQUEST_FAILED";

export const SOCKET_STOP_REQUEST = "SOCKET_STOP_REQUEST";
export const SOCKET_STOP_REQUESTING = "SOCKET_STOP_REQUESTING";
export const SOCKET_STOP_REQUEST_SUCCESSFUL = "SOCKET_STOP_REQUEST_SUCCESSFUL";
export const SOCKET_STOP_REQUEST_FAILED = "SOCKET_STOP_REQUEST_FAILED";

export const SOCKET_SUBMIT_USERID = "SOCKET_SUBMIT_USERID";
export const SOCKET_SUBMITTING_USERID = "SOCKET_SUBMITTING_USERID";
export const SOCKET_SUBMIT_USERID_SUCCESSFUL = "SOCKET_SUBMIT_USERID_SUCCESSFUL";
export const SOCKET_SUBMIT_USERID_FAILED = "SOCKET_SUBMIT_USERID_FAILED";



export const ALARM_SYSTEM_START = "ALARM_SYSTEM_START";
export const ALARM_SYSTEM_STARTED = "ALARM_SYSTEM_STARTED";

export const ALARM_PUSH_START = "ALARM_PUSH_START";
export const ALARM_PUSH_STARTING = "ALARM_PUSH_STARTING";
export const ALARM_PUSH_START_SUCCESSFUL = "ALARM_PUSH_START_SUCCESSFUL";
export const ALARM_PUSH_START_FAILED = "ALARM_PUSH_START_FAILED";

export const ALARM_PUSH_STOP = "ALARM_PUSH_STOP";
export const ALARM_PUSH_STOPPING = "ALARM_PUSH_STOPPING";
export const ALARM_PUSH_STOP_SUCCESSFUL = "ALARM_PUSH_STOP_SUCCESSFUL";
export const ALARM_PUSH_STOP_FAILED = "ALARM_PUSH_STOP_FAILED";

// Alarmer-Seite
export const ALARM_ALARM_FIRE = "ALARM_ALARM_FIRE";
export const ALARM_ALARM_FIRING = "ALARM_ALARM_FIRING";
export const ALARM_ALARM_FIRE_SUCCESSFUL = "ALARM_ALARM_FIRE_SUCCESSFUL";
export const ALARM_ALARM_FIRE_FAILED = "ALARM_ALARM_FIRE_FAILED";
export const ALARM_TESTALARM_FIRE = "ALARM_TESTALARM_FIRE";
export const ALARM_TESTALARM_FIRING = "ALARM_TESTALARM_FIRING";
export const ALARM_TESTALARM_FIRE_SUCCESSFUL = "ALARM_TESTALARM_FIRE_SUCCESSFUL";
export const ALARM_TESTALARM_FIRE_FAILED = "ALARM_TESTALARM_FIRE_FAILED";
export const ALARM_ALARM_STOP = "ALARM_ALARM_STOP";
export const ALARM_ALARM_STOPPPING = "ALARM_ALARM_STOPPPING";
export const ALARM_ALARM_STOP_SUCCESSFUL = "ALARM_ALARM_STOP_SUCCESSFUL";
export const ALARM_ALARM_STOP_FAILED = "ALARM_ALARM_STOP_FAILED";
export const ALARM_GOTCONFIRMED_RAW = "ALARM_GOTCONFIRMED_RAW";
export const ALARM_GOTCONFIRMED = "ALARM_GOTCONFIRMED";

// Confirmer-Seite
export const ALARM_GOTALARM_RAW = "ALARM_GOTALARM_RAW";
export const ALARM_GOTALARM = "ALARM_GOTALARM";
export const ALARM_GOTTESTALARM_RAW = "ALARM_GOTTESTALARM_RAW";
export const ALARM_GOTTESTALARM = "ALARM_GOTTESTALARM";
export const ALARM_GOTALARM_STOP_RAW = "ALARM_GOTALARM_STOP_RAW";
export const ALARM_CONFIRMER_ALARM_STOPPED = "ALARM_CONFIRMER_ALARM_STOPPED";
export const ALARM_CONFIRM = "ALARM_CONFIRM";
export const ALARM_CONFIRMING = "ALARM_CONFIRMING";
export const ALARM_CONFIRM_SUCCESSFUL = "ALARM_CONFIRM_SUCCESSFUL";
export const ALARM_CONFIRM_FAILED = "ALARM_CONFIRM_FAILED";
export const ALARM_TESTCONFIRM = "ALARM_CONFIRM";
export const ALARM_TESTCONFIRMING = "ALARM_CONFIRMING";
export const ALARM_TESTCONFIRM_SUCCESSFUL = "ALARM_CONFIRM_SUCCESSFUL";
export const ALARM_TESTCONFIRM_FAILED = "ALARM_CONFIRM_FAILED";
export const ALARM_CONFIRM_DENY_OR_STALE = "ALARM_CONFIRM_DENY_OR_STALE";
